# Generated by Django 3.1.7 on 2023-06-29 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='activate',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='medico',
            name='date_updated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='last_session_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='apellidos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='dni',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='n_colegiatura',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nombres',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
