# Generated by Django 3.1.7 on 2023-06-28 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('informante_atencion', '0001_initial'),
        ('diagnostico', '0001_initial'),
        ('paciente', '0001_initial'),
        ('personal_medico', '0001_initial'),
        ('medico', '0001_initial'),
        ('ubicacion_atencion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_emergencia', models.CharField(max_length=50)),
                ('tipo_atencion', models.CharField(max_length=50)),
                ('traslado', models.BooleanField(default=False)),
                ('id_diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostico.diagnostico')),
                ('id_informante_atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informante_atencion.informanteatencion')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.medico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('id_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_medico.personalmedico')),
                ('id_ubicacion_atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicacion_atencion.ubicacionatencion')),
            ],
        ),
    ]
