# Generated by Django 3.1.7 on 2023-06-29 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='activate',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paciente',
            name='date_updated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='empresa_aseguradora',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
