# Generated by Django 3.1.7 on 2023-06-29 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal_medico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmedico',
            name='activate',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='personalmedico',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='personalmedico',
            name='date_updated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personalmedico',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalmedico',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personalmedico',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalmedico',
            name='salida_cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalmedico',
            name='turno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
