# Generated by Django 3.1.7 on 2023-05-02 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_emergencia', models.CharField(max_length=50)),
                ('tipo_atencion', models.CharField(max_length=50)),
                ('traslado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MedicoEmergencia',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('n_colegiatura', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('paciente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=15)),
                ('tipo_seguro', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.IntegerField()),
                ('prioridad_emergencia', models.BooleanField()),
                ('accidente', models.BooleanField()),
                ('condicion_antes', models.TextField(blank=True, null=True)),
                ('condicion_despues', models.TextField(blank=True, null=True)),
                ('tipo_edad', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_paciente', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalMedico',
            fields=[
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20)),
                ('salida_cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionAtencion',
            fields=[
                ('id_ubicacionatencion', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=50)),
                ('sub_sector', models.CharField(max_length=50)),
                ('distrito', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('hora_salida_ambulancia', models.DateTimeField()),
                ('hora_llegada', models.DateTimeField()),
                ('hora_salida', models.DateTimeField()),
                ('hora_llegada_EESS', models.DateTimeField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samumod.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='InformanteLlamada',
            fields=[
                ('id_llamada', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_llamada', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('turno', models.CharField(max_length=50)),
                ('telefono_infor', models.CharField(max_length=20)),
                ('nombres_infor', models.CharField(max_length=50)),
                ('apellidos_infor', models.CharField(max_length=50)),
                ('dni_infor', models.CharField(max_length=20)),
                ('gen_infor', models.CharField(blank=True, max_length=20, null=True)),
                ('id_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samumod.personalmedico')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('condicion_antes', models.CharField(max_length=200)),
                ('observaciones', models.CharField(max_length=200)),
                ('condicion_despues', models.CharField(max_length=200)),
                ('derivado_EESS', models.CharField(max_length=100)),
                ('derivado_medico', models.CharField(max_length=100)),
                ('id_atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samumod.atencion')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samumod.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='atencion',
            name='id_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samumod.medicoemergencia'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samumod.paciente'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='id_personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samumod.personalmedico'),
        ),
    ]
