# Generated by Django 3.2.16 on 2023-06-29 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('informante_atencion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informanteatencion',
            name='activate',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='informanteatencion',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='informanteatencion',
            name='date_updated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='informanteatencion',
            name='apellidos_infor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='informanteatencion',
            name='dni_infor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='informanteatencion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informanteatencion',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informanteatencion',
            name='nombres_infor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='informanteatencion',
            name='telefono_infor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='informanteatencion',
            name='tipo_llamada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='informanteatencion',
            name='turno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
