# Generated by Django 3.2.16 on 2023-06-29 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='activate',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='date_updated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='condicion_antes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='condicion_despues',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='derivado_EESS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='derivado_medico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
