# Generated by Django 3.1.7 on 2023-06-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionAtencion',
            fields=[
                ('id_ubicacionatencion', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=50)),
                ('sub_sector', models.CharField(max_length=50)),
                ('distrito', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('hora_salida_ambulancia', models.DateTimeField()),
                ('hora_llegada', models.DateTimeField()),
                ('hora_salida', models.DateTimeField()),
                ('hora_llegada_EESS', models.DateTimeField()),
            ],
        ),
    ]
